# Generated by Django 5.0.6 on 2024-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="users",
        ),
    ]
