# Generated by Django 4.2.14 on 2024-07-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_role_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('not_started', 'Not Started'), ('accepted', 'Accepted')], max_length=20),
        ),
    ]
