# Generated by Django 4.2.14 on 2024-07-22 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('task_creator', 'Task Creator'), ('read_only', 'Read Only')], default='read_only', max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('role', 'user')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
    ]
